<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U443Q2A" failures="1" tests="1" name="TC_LoginDDT_002(failed)(failed)" time="10.077" errors="0" timestamp="2024-07-12T11:55:46 IST">
  <testcase classname="com.inetbanking.testCases.TC_LoginDDT_002" name="loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at com.inetbanking.testCases.TC_LoginDDT_002.getData(TC_LoginDDT_002.java:72)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- TC_LoginDDT_002(failed)(failed) -->
